### ISSUE TITLE
Эстонский язык

### ISSUE THREAD

**Issue by websil** [sim2github/yii2-redactor#4]
Добрый вечер! Отличный плагин, но к сожалению нет возможности использования на эстонском языке. Буду очень благодарен если добавите.

**Comment by sim2github** [comment]
К сожалению сам редактор не поддерживает этот язык. Вы можете перевести [существующий](https://github.com/yiiext/imperavi-redactor-widget/tree/master/assets/lang) и использовать его для своих целей.
